import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import model.Board;
import model.Player;
import service.BoardGeneratorService;
import service.SnlGameService;

public class Driver {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        List<Player> playerList = getPlayers(scanner);

        BoardGeneratorService boardGeneratorService = new BoardGeneratorService();

        /* Board generated using user input */
        // Board board = boardGeneratorService.getCustomizedBoard();

        /* Auto generated board with default values */
        Board board = boardGeneratorService.getAutoGeneratedBoard();

        SnlGameService snlGameService = new SnlGameService(board, playerList, null);
        snlGameService.startGame();
    }

    private static List<Player> getPlayers(Scanner scanner) {
        int totPlayers;
        List<Player> players = new ArrayList<>();
        System.out.println("Total Players: ");
        totPlayers = scanner.nextInt();
        for (int i = 0; i < totPlayers; i++) {
            System.out.println("Player " + i + " Name: ");
            String name = scanner.next();
            players.add(new Player(name));
        }
        return players;
    }

}
